parameters: {}
environment: {}
packages:
    - name: beach
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: beach
          runtime: python:3.11
          