# syntax=docker/dockerfile:1

FROM golang:1.21-alpine

WORKDIR /app

RUN apk add build-base

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./
COPY view ./view

RUN go build -o /beachsrv

EXPOSE 1323

CMD [ "/beachsrv" ]